name: DevSecOps Pipeline

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Vault CLI
      run: |
        sudo apt update
        sudo snap install vault 
        
    - name: Get Secret
      run: |
        export VAULT_ADDR=${{ secrets.VAULT_ADDR }}
        export VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}
        vault kv get -field=DOCKER_PASSWORD secret/myapp > secret.txt

    - name: Build Image
      run: docker build -t myapp:latest .
    
    
    - name: Scan Image
      uses: aquasecurity/trivy-action@v0.35.0
      with:
        image-ref: myapp:latest
        format: 'table'
        exit-code: '1'             # Fail the build if vulnerabilities are found
        ignore-unfixed: true       # Only show vulnerabilities with an available fix
        severity: 'CRITICAL'

    # - name: Push Image
    #   run: echo "Push to DockerHub/ECR"
